// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         goal: "goal",
 *         agentPrompt: "agentPrompt"
 *     }
 */
export interface CreateSkillRequest {
    /** Optional title for the skill (will be generated if not provided) */
    title?: string | null;
    /** Goal of the skill (description of what the skill does and what the user should expect from it) */
    goal: string;
    /** Prompt for the agent to use when generating the skill automatically */
    agentPrompt: string;
}
