// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skill_id: "skill_id"
 *     }
 */
export interface ExecuteSkillRequest {
    skill_id: string;
    /** Parameters to pass to the skill handler */
    parameters?: Record<string, unknown>;
}
