// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skill_id: "skill_id",
 *         execution_id: "execution_id"
 *     }
 */
export interface GetSkillExecutionOutputSkillsSkillIdExecutionsExecutionIdOutputGetRequest {
    skill_id: string;
    execution_id: string;
}
