// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListSkillsSkillsGetRequest {
    pageSize?: number;
    pageNumber?: number;
    isPublic?: boolean | null;
    isEnabled?: boolean | null;
    category?: BrowserUse.SkillCategory | null;
    query?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
}
