// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skill_id: "skill_id"
 *     }
 */
export interface ListSkillExecutionsSkillsSkillIdExecutionsGetRequest {
    skill_id: string;
    pageSize?: number;
    pageNumber?: number;
}
