// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSkillsSkillsGetRequest {
    pageSize?: number;
    pageNumber?: number;
    isPublic?: boolean | null;
}
