// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         skill_id: "skill_id"
 *     }
 */
export interface UpdateSkillRequest {
    skill_id: string;
    /** Display name for the skill (shows up in the public view) */
    title?: string | null;
    /** Description of what the skill does (shows up in the public view) */
    description?: string | null;
    /** Categories to assign to the skill */
    categories?: BrowserUse.SkillCategory[] | null;
    /** Domains/websites this skill interacts with */
    domains?: string[] | null;
    /** Whether the skill is enabled for execution */
    isEnabled?: boolean | null;
}
