// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skill_id: "skill_id"
 *     }
 */
export interface UpdateSkillRequest {
    skill_id: string;
    /** Display name for the skill (shows up in the public view) */
    title?: string | null;
    /** Description of what the skill does (shows up in the public view) */
    description?: string | null;
    /** Whether the skill is enabled for execution */
    isEnabled?: boolean | null;
    /** Whether the skill is publicly available */
    isPublic?: boolean | null;
}
