// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateBrowserSessionRequest {
    /** The ID of the profile to use for the session */
    profileId?: string | null;
    /** Country code for proxy location. */
    proxyCountryCode?: BrowserUse.ProxyCountryCode | null;
    /** The timeout for the session in minutes. All users can use up to 240 minutes (4 hours). Pay As You Go users are charged $0.06/hour, subscribers get 50% off. */
    timeout?: number;
    /** Custom screen width in pixels for the browser. */
    browserScreenWidth?: number | null;
    /** Custom screen height in pixels for the browser. */
    browserScreenHeight?: number | null;
    /** Whether to allow the browser to be resized during the session (not recommended since it reduces stealthiness). */
    allowResizing?: boolean;
    /** Custom proxy settings to use for the session. If not provided, our proxies will be used. Custom proxies are only available for Business and Scaleup subscribers. */
    customProxy?: BrowserUse.CustomProxy | null;
}
