/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateBrowserSessionRequest {
    /** The ID of the profile to use for the session */
    profileId?: string | null;
    /** Country code for proxy location. */
    proxyCountryCode?: BrowserUse.ProxyCountryCode | null;
    /** The timeout for the session in minutes. Free users are limited to 15 minutes, paid users can use up to 240 minutes (4 hours). */
    timeout?: number;
}
