/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         session_id: "session_id"
 *     }
 */
export interface GetBrowserSessionBrowsersSessionIdGetRequest {
    session_id: string;
}
