// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         profile_id: "profile_id"
 *     }
 */
export interface DeleteBrowserProfileProfilesProfileIdDeleteRequest {
    profile_id: string;
}
