/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         profile_id: "profile_id"
 *     }
 */
export interface ProfileUpdateRequest {
    profile_id: string;
    /** Optional name for the profile */
    name?: string | null;
}
