// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as BrowserUse from "../../../index.js";

export declare namespace Profiles {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Profiles {
    protected readonly _options: Profiles.Options;

    constructor(_options: Profiles.Options) {
        this._options = _options;
    }

    /**
     * Get paginated list of profiles.
     *
     * @param {BrowserUse.ListProfilesProfilesGetRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.profiles.listProfiles()
     */
    public listProfiles(
        request: BrowserUse.ListProfilesProfilesGetRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.ProfileListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listProfiles(request, requestOptions));
    }

    private async __listProfiles(
        request: BrowserUse.ListProfilesProfilesGetRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.ProfileListResponse>> {
        const { pageSize, pageNumber } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams.pageNumber = pageNumber.toString();
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "profiles",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.ProfileListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /profiles.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Profiles allow you to preserve the state of the browser between tasks.
     *
     * They are most commonly used to allow users to preserve the log-in state in the agent between tasks.
     * You'd normally create one profile per user and then use it for all their tasks.
     *
     * You can create a new profile by calling this endpoint.
     *
     * @param {BrowserUse.ProfileCreateRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.PaymentRequiredError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.profiles.createProfile()
     */
    public createProfile(
        request: BrowserUse.ProfileCreateRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.ProfileView> {
        return core.HttpResponsePromise.fromPromise(this.__createProfile(request, requestOptions));
    }

    private async __createProfile(
        request: BrowserUse.ProfileCreateRequest = {},
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.ProfileView>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "profiles",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.ProfileView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 402:
                    throw new BrowserUse.PaymentRequiredError(
                        _response.error.body as BrowserUse.InsufficientCreditsError,
                        _response.rawResponse,
                    );
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling POST /profiles.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get profile details.
     *
     * @param {BrowserUse.GetProfileProfilesProfileIdGetRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.profiles.getProfile({
     *         profile_id: "profile_id"
     *     })
     */
    public getProfile(
        request: BrowserUse.GetProfileProfilesProfileIdGetRequest,
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.ProfileView> {
        return core.HttpResponsePromise.fromPromise(this.__getProfile(request, requestOptions));
    }

    private async __getProfile(
        request: BrowserUse.GetProfileProfilesProfileIdGetRequest,
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.ProfileView>> {
        const { profile_id: profileId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `profiles/${core.url.encodePathParam(profileId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.ProfileView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /profiles/{profile_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Permanently delete a browser profile and its configuration.
     *
     * @param {BrowserUse.DeleteBrowserProfileProfilesProfileIdDeleteRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.profiles.deleteBrowserProfile({
     *         profile_id: "profile_id"
     *     })
     */
    public deleteBrowserProfile(
        request: BrowserUse.DeleteBrowserProfileProfilesProfileIdDeleteRequest,
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteBrowserProfile(request, requestOptions));
    }

    private async __deleteBrowserProfile(
        request: BrowserUse.DeleteBrowserProfileProfilesProfileIdDeleteRequest,
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { profile_id: profileId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `profiles/${core.url.encodePathParam(profileId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling DELETE /profiles/{profile_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update a browser profile's information.
     *
     * @param {BrowserUse.ProfileUpdateRequest} request
     * @param {Profiles.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.profiles.updateProfile({
     *         profile_id: "profile_id"
     *     })
     */
    public updateProfile(
        request: BrowserUse.ProfileUpdateRequest,
        requestOptions?: Profiles.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.ProfileView> {
        return core.HttpResponsePromise.fromPromise(this.__updateProfile(request, requestOptions));
    }

    private async __updateProfile(
        request: BrowserUse.ProfileUpdateRequest,
        requestOptions?: Profiles.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.ProfileView>> {
        const { profile_id: profileId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `profiles/${core.url.encodePathParam(profileId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.ProfileView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling PATCH /profiles/{profile_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
