/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as BrowserUse from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Browsers {
    export interface Options {
        environment?: core.Supplier<environments.BrowserUseEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Browsers {
    protected readonly _options: Browsers.Options;

    constructor(_options: Browsers.Options) {
        this._options = _options;
    }

    /**
     * Get paginated list of browser sessions with optional status filtering.
     *
     * @param {BrowserUse.ListBrowserSessionsBrowsersGetRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.listBrowserSessions()
     */
    public listBrowserSessions(
        request: BrowserUse.ListBrowserSessionsBrowsersGetRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listBrowserSessions(request, requestOptions));
    }

    private async __listBrowserSessions(
        request: BrowserUse.ListBrowserSessionsBrowsersGetRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionListResponse>> {
        const { pageSize, pageNumber, filterBy } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams["pageSize"] = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams["pageNumber"] = pageNumber.toString();
        }

        if (filterBy !== undefined) {
            _queryParams["filterBy"] = filterBy;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "browsers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.BrowserSessionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /browsers.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new browser session.
     *
     * **Pricing:** Browser sessions are charged at $0.05 per hour.
     * The full hourly rate is charged upfront when the session starts.
     * When you stop the session, any unused time is automatically refunded proportionally.
     *
     * Billing is rounded to the nearest minute (minimum 1 minute).
     * For example, if you stop a session after 30 minutes, you'll be refunded $0.025.
     *
     * **Session Limits:**
     * - Free users (without active subscription): Maximum 15 minutes per session
     * - Paid subscribers: Up to 4 hours per session
     *
     * @param {BrowserUse.CreateBrowserSessionRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.ForbiddenError}
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     * @throws {@link BrowserUse.TooManyRequestsError}
     *
     * @example
     *     await client.browsers.createBrowserSession()
     */
    public createBrowserSession(
        request: BrowserUse.CreateBrowserSessionRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionItemView> {
        return core.HttpResponsePromise.fromPromise(this.__createBrowserSession(request, requestOptions));
    }

    private async __createBrowserSession(
        request: BrowserUse.CreateBrowserSessionRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionItemView>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "browsers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionItemView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new BrowserUse.ForbiddenError(
                        _response.error.body as BrowserUse.SessionTimeoutLimitExceededError,
                        _response.rawResponse,
                    );
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new BrowserUse.TooManyRequestsError(
                        _response.error.body as BrowserUse.TooManyConcurrentActiveSessionsError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling POST /browsers.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get detailed browser session information including status and URLs.
     *
     * @param {BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.getBrowserSession({
     *         session_id: "session_id"
     *     })
     */
    public getBrowserSession(
        request: BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionView> {
        return core.HttpResponsePromise.fromPromise(this.__getBrowserSession(request, requestOptions));
    }

    private async __getBrowserSession(
        request: BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionView>> {
        const { session_id: sessionId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `browsers/${encodeURIComponent(sessionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /browsers/{session_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stop a browser session.
     *
     * **Refund:** When you stop a session, unused time is automatically refunded.
     * If the session ran for less than 1 hour, you'll receive a proportional refund.
     * Billing is ceil to the nearest minute (minimum 1 minute).
     *
     * @param {BrowserUse.UpdateBrowserSessionRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.updateBrowserSession({
     *         session_id: "session_id"
     *     })
     */
    public updateBrowserSession(
        request: BrowserUse.UpdateBrowserSessionRequest,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionView> {
        return core.HttpResponsePromise.fromPromise(this.__updateBrowserSession(request, requestOptions));
    }

    private async __updateBrowserSession(
        request: BrowserUse.UpdateBrowserSessionRequest,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionView>> {
        const { session_id: sessionId, ..._body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `browsers/${encodeURIComponent(sessionId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: { ..._body, action: "stop" },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling PATCH /browsers/{session_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
