// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as BrowserUse from "../../../index.js";

export declare namespace Browsers {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Browsers {
    protected readonly _options: Browsers.Options;

    constructor(_options: Browsers.Options = {}) {
        this._options = _options;
    }

    /**
     * Get paginated list of browser sessions with optional status filtering.
     *
     * @param {BrowserUse.ListBrowserSessionsBrowsersGetRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.listBrowserSessions()
     */
    public listBrowserSessions(
        request: BrowserUse.ListBrowserSessionsBrowsersGetRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listBrowserSessions(request, requestOptions));
    }

    private async __listBrowserSessions(
        request: BrowserUse.ListBrowserSessionsBrowsersGetRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionListResponse>> {
        const { pageSize, pageNumber, filterBy } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams.pageNumber = pageNumber.toString();
        }

        if (filterBy !== undefined) {
            _queryParams.filterBy = filterBy;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "browsers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.BrowserSessionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /browsers.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new browser session.
     *
     * **Pricing:** Browser sessions are charged per hour with tiered pricing:
     * - Pay As You Go users: $0.06/hour
     * - Business/Scaleup subscribers: $0.03/hour (50% discount)
     *
     * The full rate is charged upfront when the session starts.
     * When you stop the session, any unused time is automatically refunded proportionally.
     *
     * Billing is rounded up to the minute (minimum 1 minute).
     * For example, if you stop a session after 30 minutes, you'll be refunded half the charged amount.
     *
     * **Session Limits:**
     * - All users: Up to 4 hours per session
     *
     * @param {BrowserUse.CreateBrowserSessionRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.ForbiddenError}
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     * @throws {@link BrowserUse.TooManyRequestsError}
     *
     * @example
     *     await client.browsers.createBrowserSession()
     */
    public createBrowserSession(
        request: BrowserUse.CreateBrowserSessionRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionItemView> {
        return core.HttpResponsePromise.fromPromise(this.__createBrowserSession(request, requestOptions));
    }

    private async __createBrowserSession(
        request: BrowserUse.CreateBrowserSessionRequest = {},
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionItemView>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "browsers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionItemView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 403:
                    throw new BrowserUse.ForbiddenError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new BrowserUse.TooManyRequestsError(
                        _response.error.body as BrowserUse.TooManyConcurrentActiveSessionsError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling POST /browsers.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get detailed browser session information including status and URLs.
     *
     * @param {BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.getBrowserSession({
     *         session_id: "session_id"
     *     })
     */
    public getBrowserSession(
        request: BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionView> {
        return core.HttpResponsePromise.fromPromise(this.__getBrowserSession(request, requestOptions));
    }

    private async __getBrowserSession(
        request: BrowserUse.GetBrowserSessionBrowsersSessionIdGetRequest,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionView>> {
        const { session_id: sessionId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `browsers/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /browsers/{session_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stop a browser session.
     *
     * **Refund:** When you stop a session, unused time is automatically refunded.
     * If the session ran for less than 1 hour, you'll receive a proportional refund.
     * Billing is ceil to the nearest minute (minimum 1 minute).
     *
     * @param {BrowserUse.UpdateBrowserSessionRequest} request
     * @param {Browsers.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.browsers.updateBrowserSession({
     *         session_id: "session_id",
     *         action: "stop"
     *     })
     */
    public updateBrowserSession(
        request: BrowserUse.UpdateBrowserSessionRequest,
        requestOptions?: Browsers.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.BrowserSessionView> {
        return core.HttpResponsePromise.fromPromise(this.__updateBrowserSession(request, requestOptions));
    }

    private async __updateBrowserSession(
        request: BrowserUse.UpdateBrowserSessionRequest,
        requestOptions?: Browsers.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.BrowserSessionView>> {
        const { session_id: sessionId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `browsers/${core.url.encodePathParam(sessionId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.BrowserSessionView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling PATCH /browsers/{session_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
