/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         execution_id: "execution_id"
 *     }
 */
export interface CancelExecutionWorkflowsExecutionsExecutionIdCancelPatchRequest {
    execution_id: string;
}
