// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflow_id: "workflow_id"
 *     }
 */
export interface GetWorkflowWorkflowsWorkflowIdGetRequest {
    workflow_id: string;
}
