/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         workflow_id: "workflow_id"
 *     }
 */
export interface ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetRequest {
    workflow_id: string;
    pageSize?: number;
    pageNumber?: number;
    status?: BrowserUse.WorkflowExecutionStatus | null;
    workflowId?: string | null;
}
