// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListWorkflowsWorkflowsGetRequest {
    pageSize?: number;
    pageNumber?: number;
    isArchived?: boolean;
    userId?: string | null;
}
