// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflow_id: "workflow_id"
 *     }
 */
export interface WorkflowExecuteRequest {
    workflow_id: string;
    /** Input parameters for the workflow execution */
    input?: Record<string, unknown> | null;
    /** Optional metadata for this execution */
    executionMetadata?: Record<string, unknown> | null;
}
