// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         workflow_id: "workflow_id",
 *         sizeBytes: 1
 *     }
 */
export interface WorkflowYamlPresignedUploadRequest {
    workflow_id: string;
    /** The name of the YAML file to upload */
    fileName?: string;
    /** Size of the YAML file in bytes */
    sizeBytes: number;
}
