/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         workflow_id: "workflow_id",
 *         taskPrompt: "Go to github.com and search for browser-use"
 *     }
 */
export interface WorkflowGenerateRequest {
    workflow_id: string;
    /** Natural language description of the task to automate */
    taskPrompt: string;
    /** Optional name for the generated workflow. If not provided, will be inferred from prompt. */
    workflowName?: string | null;
    /** Whether to extract reusable variables from the workflow */
    enableVariableExtraction?: boolean;
    /** Whether to use deterministic conversion (faster and cheaper) */
    useDeterministicConversion?: boolean;
    /** Whether to use cloud browser for recording (recommended for production) */
    useCloudBrowser?: boolean;
    /** Enable pattern-based variable identification (no LLM, $0 cost) */
    enablePatternVariableIdentification?: boolean;
    /** Minimum confidence threshold for pattern-based detection (0.0 to 1.0) */
    patternVariableConfidence?: number;
    /** Enable AI validation to review and fix generated workflow */
    enableAiValidation?: boolean;
    /** Remove verbose fields from generated YAML */
    cleanupYaml?: boolean;
    /** Remove step descriptions (only if cleanup_yaml=True) */
    removeDescriptions?: boolean;
    /** Remove verification_checks (only if cleanup_yaml=True) */
    removeVerificationChecks?: boolean;
    /** Remove expected_outcome fields (only if cleanup_yaml=True) */
    removeExpectedOutcomes?: boolean;
    /** Remove agent_reasoning fields (only if cleanup_yaml=True) */
    removeAgentReasoning?: boolean;
}
