// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface WorkflowCreateRequest {
    /** Name of the workflow */
    name: string;
    /** Optional description of the workflow */
    description?: string | null;
    /** Optional variables/parameters for the workflow */
    variables?: Record<string, unknown> | null;
}
