/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         workflow_id: "workflow_id"
 *     }
 */
export interface WorkflowUpdateRequest {
    workflow_id: string;
    /** Name of the workflow */
    name?: string | null;
    /** Description of the workflow */
    description?: string | null;
    /** Variables/parameters for the workflow */
    variables?: Record<string, unknown> | null;
}
