// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         skill_id: "skill_id",
 *         body: {}
 *     }
 */
export interface ExecuteSkillMarketplaceSkillsSkillIdExecutePostRequest {
    skill_id: string;
    body: BrowserUse.ExecuteSkillRequest;
}
