// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         skill_slug: "skill_slug"
 *     }
 */
export interface GetSkillMarketplaceSkillsSkillSlugGetRequest {
    skill_slug: string;
}
