// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListSkillsMarketplaceSkillsGetRequest {
    pageSize?: number;
    pageNumber?: number;
    query?: string | null;
    fromDate?: string | null;
    toDate?: string | null;
}
