// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as BrowserUse from "../../../index.js";

export declare namespace Tasks {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class Tasks {
    protected readonly _options: Tasks.Options;

    constructor(_options: Tasks.Options = {}) {
        this._options = _options;
    }

    /**
     * Get paginated list of AI agent tasks with optional filtering by session and status.
     *
     * @param {BrowserUse.ListTasksTasksGetRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.tasks.listTasks()
     */
    public listTasks(
        request: BrowserUse.ListTasksTasksGetRequest = {},
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.TaskListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listTasks(request, requestOptions));
    }

    private async __listTasks(
        request: BrowserUse.ListTasksTasksGetRequest = {},
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.TaskListResponse>> {
        const { pageSize, pageNumber, sessionId, filterBy, after, before } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams.pageNumber = pageNumber.toString();
        }

        if (sessionId !== undefined) {
            _queryParams.sessionId = sessionId;
        }

        if (filterBy !== undefined) {
            _queryParams.filterBy = filterBy;
        }

        if (after !== undefined) {
            _queryParams.after = after;
        }

        if (before !== undefined) {
            _queryParams.before = before;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "tasks",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.TaskListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /tasks.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create and start a new task.
     *
     * You can either:
     * 1. Start a new task without a sessionId (auto-creates a session with US proxy by default)
     * 2. Start a new task in an existing session (reuse for follow-up tasks or custom configuration)
     *
     * Important: Proxy configuration (proxyCountryCode) is a session-level setting, not a task-level setting.
     * To use a custom proxy location, create a session first via POST /sessions with your desired proxyCountryCode,
     * then pass that sessionId when creating tasks.
     *
     * @param {BrowserUse.CreateTaskRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.BadRequestError}
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     * @throws {@link BrowserUse.TooManyRequestsError}
     *
     * @example
     *     await client.tasks.createTask({
     *         task: "task"
     *     })
     */
    public createTask(
        request: BrowserUse.CreateTaskRequest,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.TaskCreatedResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createTask(request, requestOptions));
    }

    private async __createTask(
        request: BrowserUse.CreateTaskRequest,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.TaskCreatedResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "tasks",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.TaskCreatedResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrowserUse.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 429:
                    throw new BrowserUse.TooManyRequestsError(
                        _response.error.body as BrowserUse.TooManyConcurrentActiveSessionsError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling POST /tasks.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get detailed task information including status, progress, steps, and file outputs.
     *
     * @param {BrowserUse.GetTaskTasksTaskIdGetRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.tasks.getTask({
     *         task_id: "task_id"
     *     })
     */
    public getTask(
        request: BrowserUse.GetTaskTasksTaskIdGetRequest,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.TaskView> {
        return core.HttpResponsePromise.fromPromise(this.__getTask(request, requestOptions));
    }

    private async __getTask(
        request: BrowserUse.GetTaskTasksTaskIdGetRequest,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.TaskView>> {
        const { task_id: taskId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.TaskView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /tasks/{task_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Control task execution with stop, pause, resume, or stop task and session actions.
     *
     * @param {BrowserUse.UpdateTaskRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.tasks.updateTask({
     *         task_id: "task_id",
     *         action: "stop"
     *     })
     */
    public updateTask(
        request: BrowserUse.UpdateTaskRequest,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.TaskView> {
        return core.HttpResponsePromise.fromPromise(this.__updateTask(request, requestOptions));
    }

    private async __updateTask(
        request: BrowserUse.UpdateTaskRequest,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.TaskView>> {
        const { task_id: taskId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.TaskView, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling PATCH /tasks/{task_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get secure download URL for task execution logs with step-by-step details.
     *
     * @param {BrowserUse.GetTaskLogsTasksTaskIdLogsGetRequest} request
     * @param {Tasks.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     * @throws {@link BrowserUse.InternalServerError}
     *
     * @example
     *     await client.tasks.getTaskLogs({
     *         task_id: "task_id"
     *     })
     */
    public getTaskLogs(
        request: BrowserUse.GetTaskLogsTasksTaskIdLogsGetRequest,
        requestOptions?: Tasks.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.TaskLogFileResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getTaskLogs(request, requestOptions));
    }

    private async __getTaskLogs(
        request: BrowserUse.GetTaskLogsTasksTaskIdLogsGetRequest,
        requestOptions?: Tasks.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.TaskLogFileResponse>> {
        const { task_id: taskId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `tasks/${core.url.encodePathParam(taskId)}/logs`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.TaskLogFileResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                case 500:
                    throw new BrowserUse.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /tasks/{task_id}/logs.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
