/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateSessionRequest {
    profileId?: string;
    proxy?: BrowserUse.ProxySettings;
}
