// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateSessionRequest {
    /** The ID of the profile to use for the session */
    profileId?: string | null;
    /** Country code for proxy location. */
    proxyCountryCode?: BrowserUse.ProxyCountryCode | null;
    /** URL to navigate to when the session starts. */
    startUrl?: string | null;
    /** Custom screen width in pixels for the browser. */
    browserScreenWidth?: number | null;
    /** Custom screen height in pixels for the browser. */
    browserScreenHeight?: number | null;
}
