/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateSessionRequest {
    /** The ID of the profile to use for the session */
    profileId?: string;
    /** Proxy settings for the session */
    proxy?: BrowserUse.ProxySettings;
}
