// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         task_id: "task_id"
 *     }
 */
export interface GetTaskStatusTasksTaskIdStatusGetRequest {
    task_id: string;
}
