/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListTasksTasksGetRequest {
    pageSize?: number;
    pageNumber?: number;
    sessionId?: string | null;
    filterBy?: BrowserUse.TaskStatus | null;
    after?: string | null;
    before?: string | null;
}
