// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         task_id: "task_id",
 *         action: "stop"
 *     }
 */
export interface UpdateTaskRequest {
    task_id: string;
    /** The action to perform on the task */
    action: BrowserUse.TaskUpdateAction;
}
