/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * View model for account information
 */
export interface AccountView {
    /** The name of the user */
    name?: string | null;
    /** The monthly credits balance in USD */
    monthlyCreditsBalanceUsd: number;
    /** The additional credits balance in USD */
    additionalCreditsBalanceUsd: number;
    /** The total credits balance in USD */
    totalCreditsBalanceUsd: number;
    /** The rate limit for the account */
    rateLimit: number;
    /** The plan information */
    planInfo: BrowserUse.PlanInfo;
    /** The ID of the project */
    projectId: string;
}
