// This file was auto-generated by Fern from our API Definition.

/**
 * Error response when there are insufficient credits
 */
export interface AppApiV2SkillsViewsInsufficientCreditsError {
    detail?: string;
}
