// This file was auto-generated by Fern from our API Definition.

/**
 * Available actions that can be performed on a browser session
 *
 * Attributes:
 *     STOP: Stop the browser session (cannot be undone)
 */
export type BrowserSessionUpdateAction = "stop";
