// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * View model for representing a browser session.
 */
export interface BrowserSessionView {
    /** Unique identifier for the session */
    id: string;
    /** Current status of the session (active/stopped) */
    status: BrowserUse.BrowserSessionStatus;
    /** URL where the browser can be viewed live in real-time */
    liveUrl?: string | null;
    /** Chrome DevTools Protocol URL for browser automation */
    cdpUrl?: string | null;
    /** Timestamp when the session will timeout */
    timeoutAt: string;
    /** Timestamp when the session was created and started */
    startedAt: string;
    /** Timestamp when the session was stopped (None if still active) */
    finishedAt?: string | null;
    /** Amount of proxy data used in MB */
    proxyUsedMb?: string;
    /** Cost of proxy usage in USD */
    proxyCost?: string;
    /** Cost of browser session hosting in USD */
    browserCost?: string;
}
