// This file was auto-generated by Fern from our API Definition.

/**
 * Error response when a skill cannot be deleted while it is still generating
 */
export interface CannotDeleteSkillWhileGeneratingError {
    detail?: string;
}
