// This file was auto-generated by Fern from our API Definition.

/**
 * Error response when concurrent skill creations are attempted
 */
export interface ConcurrentSkillCreationsError {
    detail?: string;
}
