// This file was auto-generated by Fern from our API Definition.

/**
 * Response after creating a skill.
 */
export interface CreateSkillResponse {
    /** Unique identifier for the created skill */
    id: string;
}
