// This file was auto-generated by Fern from our API Definition.

/**
 * Request model for creating a custom proxy.
 */
export interface CustomProxy {
    /** Host of the proxy. */
    host: string;
    /** Port of the proxy. */
    port: number;
    /** Username for proxy authentication. */
    username?: string | null;
    /** Password for proxy authentication. */
    password?: string | null;
}
