// This file was auto-generated by Fern from our API Definition.

/**
 * Error response when trying to enable more skills than allowed by plan
 */
export interface EnabledSkillsLimitExceededError {
    detail?: string;
}
