// This file was auto-generated by Fern from our API Definition.

/**
 * Execution mode for workflows.
 *
 * Attributes:
 *         ASYNC: Asynchronous execution via workflow_worker Lambda
 *         SYNC: Synchronous execution with response inline
 */
export const ExecutionMode = {
    Async: "async",
    Sync: "sync",
} as const;
export type ExecutionMode = (typeof ExecutionMode)[keyof typeof ExecutionMode];
