// This file was auto-generated by Fern from our API Definition.

/**
 * View model for representing an output file generated by the agent
 */
export interface FileView {
    /** Unique identifier for the output file */
    id: string;
    /** Name of the output file */
    fileName: string;
}
