// This file was auto-generated by Fern from our API Definition.

/** Type of a skill parameter. */
export const ParameterType = {
    String: "string",
    Number: "number",
    Boolean: "boolean",
    Object: "object",
    Array: "array",
    Cookie: "cookie",
} as const;
export type ParameterType = (typeof ParameterType)[keyof typeof ParameterType];
