// This file was auto-generated by Fern from our API Definition.

/**
 * View model for representing a profile. A profile lets you preserve the login state between sessions.
 *
 * We recommend that you create a separate profile for each user of your app.
 */
export interface ProfileView {
    /** Unique identifier for the profile */
    id: string;
    /** Optional name for the profile */
    name?: string | null;
    /** Timestamp when the profile was last used */
    lastUsedAt?: string | null;
    /** Timestamp when the profile was created */
    createdAt: string;
    /** Timestamp when the profile was last updated */
    updatedAt: string;
    /** List of domain URLs that have cookies stored for this profile */
    cookieDomains?: string[] | null;
}
