/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing a profile. A profile lets you preserve the login state between sessions.
 *
 * We recommend that you create a separate profile for each user of your app.
 *
 * Attributes:
 *     id: Unique identifier for the profile
 *
 *         last_used_at: Timestamp when the profile was last used
 *
 *     created_at: Timestamp when the profile was created
 *     updated_at: Timestamp when the profile was last updated
 */
export interface ProfileView {
    id: string;
    lastUsedAt?: string;
    createdAt: string;
    updatedAt: string;
}
