/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Proxy configuration settings.
 */
export interface ProxySettings {
    /** Whether proxy is enabled */
    enable?: boolean;
    /** Country code for proxy location */
    proxyCountryCode?: BrowserUse.ProxyCountryCode;
}
