// This file was auto-generated by Fern from our API Definition.

/**
 * Error response when session timeout exceeds the maximum allowed limit
 */
export interface SessionTimeoutLimitExceededError {
    detail?: string;
}
