// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Response model for paginated session list requests.
 */
export interface SessionListResponse {
    /** List of session views for the current page */
    items: BrowserUse.SessionItemView[];
    /** Total number of items in the list */
    totalItems: number;
    /** Page number */
    pageNumber: number;
    /** Number of items per page */
    pageSize: number;
}
