// This file was auto-generated by Fern from our API Definition.

/**
 * Available actions that can be performed on a session
 *
 * Attributes:
 *     STOP: Stop the session and all its associated tasks (cannot be undone)
 */
export const SessionUpdateAction = {
    Stop: "stop",
} as const;
export type SessionUpdateAction = (typeof SessionUpdateAction)[keyof typeof SessionUpdateAction];
