/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Error response when free user tries to create session longer than allowed
 */
export interface SessionTimeoutLimitExceededError {
    detail?: string;
}
