// This file was auto-generated by Fern from our API Definition.

/**
 * Enumeration of possible agent session states
 *
 * Attributes:
 *     ACTIVE: Agent session is currently active and running
 *     STOPPED: Agent session has been stopped and is no longer active
 */
export const SessionStatus = {
    Active: "active",
    Stopped: "stopped",
} as const;
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];
