/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * View model for representing a (browser) session.
 */
export interface SessionItemView {
    /** Unique identifier for the session */
    id: string;
    /** Current status of the session (active/stopped) */
    status: BrowserUse.SessionStatus;
    /** URL where the browser can be viewed live in real-time */
    liveUrl?: string;
    /** Timestamp when the session was created and started */
    startedAt: string;
    /** Timestamp when the session was stopped (None if still active) */
    finishedAt?: string;
}
