/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing a public share of a session.
 */
export interface ShareView {
    /** Token to access the public share */
    shareToken: string;
    /** URL to access the public share */
    shareUrl: string;
    /** Number of times the public share has been viewed */
    viewCount: number;
    /** Timestamp of the last time the public share was viewed (None if never viewed) */
    lastViewedAt?: string | null;
}
