// This file was auto-generated by Fern from our API Definition.

/** Status of skill generation. */
export const SkillsGenerationStatus = {
    Recording: "recording",
    Generating: "generating",
    Failed: "failed",
    Finished: "finished",
    Cancelled: "cancelled",
} as const;
export type SkillsGenerationStatus = (typeof SkillsGenerationStatus)[keyof typeof SkillsGenerationStatus];
