// This file was auto-generated by Fern from our API Definition.

/**
 * View for a skill execution.
 */
export interface SkillExecutionView {
    /** Unique identifier for the execution */
    id: string;
    /** ID of the skill that was executed */
    skillId: string;
    /** Execution status (running, completed, failed) */
    status: string;
    /** Whether the execution succeeded */
    success: boolean;
    /** When the execution started */
    startedAt: string;
    /** When the execution finished */
    finishedAt: string | null;
    /** Execution latency in milliseconds */
    latencyMs: number | null;
    /** Whether output is available for download */
    hasOutput: boolean;
}
