// This file was auto-generated by Fern from our API Definition.

/**
 * Response containing presigned URL for downloading execution output.
 */
export interface SkillExecutionOutputResponse {
    /** Presigned URL for downloading the execution output (valid for 5 minutes) */
    downloadUrl: string;
}
