// This file was auto-generated by Fern from our API Definition.

/** Skill category. */
export const SkillCategory = {
    Search: "search",
    ECommerce: "e_commerce",
    Financial: "financial",
    News: "news",
    RealEstate: "real_estate",
    SocialMedia: "social_media",
    Travel: "travel",
    Marketplace: "marketplace",
    LeadGeneration: "lead_generation",
    Seo: "seo",
    Jobs: "jobs",
    Developer: "developer",
    Media: "media",
    Automation: "automation",
    Integration: "integration",
    Other: "other",
} as const;
export type SkillCategory = (typeof SkillCategory)[keyof typeof SkillCategory];
