// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Response for listing skill executions.
 */
export interface SkillExecutionListResponse {
    /** List of executions */
    items: BrowserUse.SkillExecutionView[];
    /** Total number of items in the list */
    totalItems: number;
    /** Page number */
    pageNumber: number;
    /** Number of items per page */
    pageSize: number;
}
