/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * View model for representing a task with its execution details
 */
export interface TaskItemView {
    /** Unique identifier for the task */
    id: string;
    /** ID of the session this task belongs to */
    sessionId: string;
    /** The LLM model used for this task represented as a string */
    llm: string;
    /** The task prompt/instruction given to the agent */
    task: string;
    status: BrowserUse.TaskStatus;
    /** Naive UTC timestamp when the task was started */
    startedAt: string;
    /** Naive UTC timestamp when the task completed (None if still running) */
    finishedAt?: string;
    /** Optional additional metadata associated with the task set by the user */
    metadata?: Record<string, unknown>;
    /** Final output/result of the task */
    output?: string;
    /** Version of browser-use used for this task (older tasks may not have this set) */
    browserUseVersion?: string;
    /** Whether the task was successful (self-reported by the agent) */
    isSuccess?: boolean;
}
