/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for creating a task
 */
export interface TaskCreatedResponse {
    /** Unique identifier for the created task */
    id: string;
}
