// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * View model for representing a task with its execution details
 */
export interface TaskItemView {
    /** Unique identifier for the task */
    id: string;
    /** ID of the session this task belongs to */
    sessionId: string;
    /** The LLM model used for this task represented as a string */
    llm: string;
    /** The task prompt/instruction given to the agent */
    task: string;
    status: BrowserUse.TaskStatus;
    /** Naive UTC timestamp when the task was created */
    createdAt: string;
    /** Naive UTC timestamp when the task was started (None if task has not started yet) */
    startedAt?: string | null;
    /** Naive UTC timestamp when the task completed (None if still running) */
    finishedAt?: string | null;
    /** Optional additional metadata associated with the task set by the user */
    metadata?: Record<string, unknown>;
    /** Final output/result of the task */
    output?: string | null;
    /** Version of browser-use used for this task (older tasks may not have this set) */
    browserUseVersion?: string | null;
    /** Whether the task was successful (self-reported by the agent) */
    isSuccess?: boolean | null;
    /** Stringified JSON object containing the full report from the judge */
    judgement?: string | null;
    /** Judge verdict - True if the judge found the task to be successful, False otherwise (None if judge is not enabled) */
    judgeVerdict?: boolean | null;
    /** Total cost of the task in USD. This is the sum of all step costs incurred during task execution. */
    cost?: string | null;
}
