// This file was auto-generated by Fern from our API Definition.

/**
 * Available actions that can be performed on a task
 *
 * Attributes:
 *     STOP: Stop the current task execution
 *     STOP_TASK_AND_SESSION: Stop both the task and its parent session
 */
export const TaskUpdateAction = {
    Stop: "stop",
    StopTaskAndSession: "stop_task_and_session",
} as const;
export type TaskUpdateAction = (typeof TaskUpdateAction)[keyof typeof TaskUpdateAction];
