/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for paginated task list requests.
 */
export interface TaskListResponse {
    /** List of task views for the current page */
    items: BrowserUse.TaskItemView[];
    /** Total number of items in the list */
    totalItems: number;
    /** Page number */
    pageNumber: number;
    /** Number of items per page */
    pageSize: number;
}
