/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for log file requests
 */
export interface TaskLogFileResponse {
    /** URL to download the log file */
    downloadUrl: string;
}
