// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Lightweight view optimized for polling. Use GET /tasks/{id}/status for efficient polling
 * instead of GET /tasks/{id} which loads full step details.
 */
export interface TaskStatusView {
    /** Unique identifier for the task */
    id: string;
    /** Current status of the task */
    status: BrowserUse.TaskStatus;
    /** Final output/result of the task (null while running) */
    output?: string | null;
    /** Naive UTC timestamp when the task completed (null if still running) */
    finishedAt?: string | null;
    /** Whether the task was successful based on the agent's self-reported output */
    isSuccess?: boolean | null;
    /** Total cost of the task in USD */
    cost?: string | null;
}
