/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response model for creating a task
 *
 * Attributes:
 *         id: Unique identifier for the created task
 */
export interface TaskCreatedResponse {
    id: string;
}
