/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Enumeration of possible task execution states
 *
 * Attributes:
 *         CREATED: Task has been created but not yet started.
 *     STARTED: Task has been started and is currently running.
 *     FINISHED: Task has finished and the agent has completed the task.
 *     STOPPED: Task execution has been manually stopped (cannot be resumed).
 */
export type TaskStatus = "created" | "started" | "finished" | "stopped";
export const TaskStatus = {
    Created: "created",
    Started: "started",
    Finished: "finished",
    Stopped: "stopped",
} as const;
