/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * View model for representing a single step in a task's execution
 */
export interface TaskStepView {
    /** Sequential step number within the task */
    number: number;
    /** Agent's memory at this step */
    memory: string;
    /** Agent's evaluation of the previous goal completion */
    evaluationPreviousGoal: string;
    /** The goal for the next step */
    nextGoal: string;
    /** Current URL the browser is on for this step */
    url: string;
    /** Optional URL to the screenshot taken at this step */
    screenshotUrl?: string | null;
    /** List of stringified json actions performed by the agent in this step */
    actions: string[];
}
