/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for paginated execution list requests.
 */
export interface WorkflowExecutionListResponse {
    /** List of executions for the current page */
    items: BrowserUse.WorkflowExecutionItemView[];
    /** Total number of items in the list */
    totalItems: number;
    /** Page number */
    pageNumber: number;
    /** Number of items per page */
    pageSize: number;
}
