// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * View model for workflow execution state (used for polling during execution).
 */
export interface WorkflowExecutionStateView {
    /** Unique identifier for the execution */
    id: string;
    /** ID of the workflow being executed */
    workflowId: string;
    /** Current status of the execution */
    status: BrowserUse.WorkflowExecutionStatus;
    /** When execution started */
    startedAt?: string | null;
    /** When execution finished */
    finishedAt?: string | null;
    /** List of execution steps with details */
    steps?: BrowserUse.WorkflowExecutionStepView[];
    /** LLM costs for this execution */
    llmsCost?: string;
    /** Initialization costs */
    initCost?: string;
    /** Total cost */
    totalCost?: string;
    /** When execution was created */
    createdAt: string;
    /** Live browser view URL (available during and up to 60s after execution) */
    liveUrl?: string | null;
}
