// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Minimal view model for listing workflows.
 */
export interface WorkflowItemView {
    /** Unique identifier for the workflow */
    id: string;
    /** Name of the workflow */
    name: string;
    /** Description of the workflow */
    description?: string | null;
    /** Variables/parameters for the workflow */
    variables?: Record<string, unknown>;
    /** Total cost incurred by this workflow */
    cost?: string;
    /** Whether the workflow is archived */
    isArchived?: boolean;
    /** Status of workflow generation */
    generationStatus?: BrowserUse.WorkflowGenerationStatus;
    /** Error message if generation failed */
    generationError?: string | null;
    /** Generation metadata including progress_step */
    generationMetadata?: Record<string, unknown> | null;
    /** Naive UTC timestamp when the workflow was created */
    createdAt: string;
}
