// This file was auto-generated by Fern from our API Definition.

/** Status of workflow YAML generation. */
export const WorkflowGenerationStatus = {
    Pending: "pending",
    Generating: "generating",
    Completed: "completed",
    Failed: "failed",
} as const;
export type WorkflowGenerationStatus = (typeof WorkflowGenerationStatus)[keyof typeof WorkflowGenerationStatus];
