// This file was auto-generated by Fern from our API Definition.

/**
 * Minimal view of a step for media endpoint (screenshots only).
 */
export interface WorkflowExecutionMediaStepView {
    /** Unique identifier for the step */
    id: string;
    /** Description of what this step did */
    nextGoal: string;
    /** Presigned URL for the step screenshot */
    screenshotUrl?: string | null;
    /** Actions taken in this step */
    actions?: Record<string, unknown>[];
}
