/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../index.js";

/**
 * Response model for a single workflow.
 */
export interface WorkflowResponse {
    /** Unique identifier for the workflow */
    id: string;
    /** Project ID this workflow belongs to */
    projectId: string;
    /** User ID who created the workflow */
    userId?: string | null;
    /** Name of the workflow */
    name: string;
    /** Description of the workflow */
    description?: string | null;
    /** S3 key where the workflow YAML is stored */
    s3Key?: string | null;
    /** Presigned URL to download the workflow YAML */
    yamlDownloadUrl?: string | null;
    /** Variables/parameters for the workflow */
    variables?: Record<string, unknown>;
    /** Total cost incurred by this workflow */
    cost?: string;
    /** Whether the workflow is archived */
    isArchived?: boolean;
    /** Status of workflow YAML generation */
    generationStatus?: BrowserUse.WorkflowGenerationStatus;
    /** Error message if generation failed */
    generationError?: string | null;
    /** Input schema from workflow YAML defining required/optional variables */
    inputSchema?: Record<string, unknown>[] | null;
    /** Pre-filled input template based on input_schema for easy execution */
    inputTemplate?: Record<string, unknown> | null;
    /** Naive UTC timestamp when the workflow was created */
    createdAt: string;
    /** Naive UTC timestamp when the workflow was last updated */
    updatedAt: string;
}
