// This file was auto-generated by Fern from our API Definition.

/**
 * Status of workflow execution.
 *
 * Attributes:
 *         PENDING: Execution has been created but not started
 *         RUNNING: Execution is currently in progress
 *         COMPLETED: Execution finished successfully
 *         FAILED: Execution failed with errors
 *         CANCELLED: Execution was cancelled by user
 */
export const WorkflowExecutionStatus = {
    Pending: "pending",
    Running: "running",
    Completed: "completed",
    Failed: "failed",
    Cancelled: "cancelled",
} as const;
export type WorkflowExecutionStatus = (typeof WorkflowExecutionStatus)[keyof typeof WorkflowExecutionStatus];
