// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Response model for a workflow execution.
 */
export interface WorkflowExecutionResponse {
    /** Unique identifier for the execution */
    id: string;
    /** ID of the workflow being executed */
    workflowId: string;
    /** User ID who triggered the execution */
    userId?: string | null;
    /** Current status of the execution */
    status: BrowserUse.WorkflowExecutionStatus;
    /** Naive UTC timestamp when execution started */
    startedAt?: string | null;
    /** Naive UTC timestamp when execution finished */
    finishedAt?: string | null;
    /** Time taken for execution in seconds */
    timeTaken?: number | null;
    /** LLM costs for this execution */
    llmsCost?: string;
    /** Initialization costs for this execution */
    initCost?: string;
    /** Total cost for this execution */
    totalCost?: string;
    /** Input parameters used for execution */
    input?: Record<string, unknown> | null;
    /** Output/results from the execution */
    output?: Record<string, unknown> | null;
    /** Errors encountered during execution */
    errors?: Record<string, unknown> | null;
    /** Metadata for this execution */
    executionMetadata?: Record<string, unknown> | null;
    /** Presigned URL to download execution logs */
    logsDownloadUrl?: string | null;
    /** AI-generated summary of the execution result */
    aiSummary?: string | null;
    /** AI's determination of whether execution succeeded */
    aiSuccess?: boolean | null;
    /** Naive UTC timestamp when execution was created */
    createdAt: string;
}
