// This file was auto-generated by Fern from our API Definition.

import type * as BrowserUse from "../index.js";

/**
 * Response model for creating a workflow execution (async mode).
 */
export interface WorkflowExecutionCreatedResponse {
    /** Unique identifier for the execution */
    id: string;
    /** ID of the workflow being executed */
    workflowId: string;
    /** Current status of the execution */
    status: BrowserUse.WorkflowExecutionStatus;
}
