// This file was auto-generated by Fern from our API Definition.

/**
 * Response model for workflow created from an agent task.
 */
export interface WorkflowCreateFromTaskResponse {
    /** ID of the newly created workflow */
    workflowId: string;
    /** Status of the workflow creation (pending, completed) */
    status?: string;
    /** Human-readable message about the creation */
    message?: string;
}
