// This file was auto-generated by Fern from our API Definition.

/**
 * Response model for presigned URL to upload workflow YAML.
 */
export interface WorkflowYamlPresignedUploadResponse {
    /** The URL to upload the YAML file to */
    url: string;
    /** The HTTP method to use for the upload */
    method: WorkflowYamlPresignedUploadResponse.Method;
    /** The form fields to include in the upload request */
    fields: Record<string, string>;
    /** The S3 key where the file will be stored */
    s3Key: string;
    /** Number of seconds until the presigned URL expires */
    expiresIn: number;
}

export namespace WorkflowYamlPresignedUploadResponse {
    /** The HTTP method to use for the upload */
    export const Method = {
        Post: "POST",
    } as const;
    export type Method = (typeof Method)[keyof typeof Method];
}
