/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as BrowserUse from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Workflows {
    export interface Options {
        environment?: core.Supplier<environments.BrowserUseEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        apiKey: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class Workflows {
    protected readonly _options: Workflows.Options;

    constructor(_options: Workflows.Options) {
        this._options = _options;
    }

    /**
     * Get paginated list of workflows with optional filtering.
     *
     * @param {BrowserUse.ListWorkflowsWorkflowsGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.listWorkflows()
     */
    public listWorkflows(
        request: BrowserUse.ListWorkflowsWorkflowsGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listWorkflows(request, requestOptions));
    }

    private async __listWorkflows(
        request: BrowserUse.ListWorkflowsWorkflowsGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowListResponse>> {
        const { pageSize, pageNumber, isArchived, userId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams["pageSize"] = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams["pageNumber"] = pageNumber.toString();
        }

        if (isArchived != null) {
            _queryParams["isArchived"] = isArchived.toString();
        }

        if (userId !== undefined) {
            _queryParams["userId"] = userId;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "workflows",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowListResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /workflows.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Create a new workflow. The workflow YAML should be uploaded separately via the update endpoint.
     *
     * @param {BrowserUse.WorkflowCreateRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.createWorkflow({
     *         name: "name"
     *     })
     */
    public createWorkflow(
        request: BrowserUse.WorkflowCreateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createWorkflow(request, requestOptions));
    }

    private async __createWorkflow(
        request: BrowserUse.WorkflowCreateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowResponse>> {
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "workflows",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling POST /workflows.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get detailed workflow information including presigned URL to download YAML.
     *
     * @param {BrowserUse.GetWorkflowWorkflowsWorkflowIdGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getWorkflow({
     *         workflow_id: "workflow_id"
     *     })
     */
    public getWorkflow(
        request: BrowserUse.GetWorkflowWorkflowsWorkflowIdGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWorkflow(request, requestOptions));
    }

    private async __getWorkflow(
        request: BrowserUse.GetWorkflowWorkflowsWorkflowIdGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowResponse>> {
        const { workflow_id: workflowId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /workflows/{workflow_id}.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Archive a workflow (soft delete).
     *
     * @param {BrowserUse.DeleteWorkflowWorkflowsWorkflowIdDeleteRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.deleteWorkflow({
     *         workflow_id: "workflow_id"
     *     })
     */
    public deleteWorkflow(
        request: BrowserUse.DeleteWorkflowWorkflowsWorkflowIdDeleteRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowResponse> {
        return core.HttpResponsePromise.fromPromise(this.__deleteWorkflow(request, requestOptions));
    }

    private async __deleteWorkflow(
        request: BrowserUse.DeleteWorkflowWorkflowsWorkflowIdDeleteRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowResponse>> {
        const { workflow_id: workflowId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling DELETE /workflows/{workflow_id}.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update workflow metadata.
     *
     * @param {BrowserUse.WorkflowUpdateRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.updateWorkflow({
     *         workflow_id: "workflow_id"
     *     })
     */
    public updateWorkflow(
        request: BrowserUse.WorkflowUpdateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateWorkflow(request, requestOptions));
    }

    private async __updateWorkflow(
        request: BrowserUse.WorkflowUpdateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowResponse>> {
        const { workflow_id: workflowId, ..._body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling PATCH /workflows/{workflow_id}.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get a presigned URL to upload workflow YAML directly to S3 from the browser.
     *
     * This avoids sending the YAML content through the backend, reducing latency
     * and avoiding KMS permission issues in local development.
     *
     * @param {BrowserUse.WorkflowYamlPresignedUploadRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getWorkflowYamlPresignedUrl({
     *         workflow_id: "workflow_id",
     *         sizeBytes: 1
     *     })
     */
    public getWorkflowYamlPresignedUrl(
        request: BrowserUse.WorkflowYamlPresignedUploadRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowYamlPresignedUploadResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getWorkflowYamlPresignedUrl(request, requestOptions));
    }

    private async __getWorkflowYamlPresignedUrl(
        request: BrowserUse.WorkflowYamlPresignedUploadRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowYamlPresignedUploadResponse>> {
        const { workflow_id: workflowId, ..._body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}/yaml/presigned-url`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.WorkflowYamlPresignedUploadResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling POST /workflows/{workflow_id}/yaml/presigned-url.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Execute a workflow either synchronously or asynchronously.
     *
     * - ASYNC mode: Returns execution ID immediately and processes in background via Lambda
     * - SYNC mode: Waits for execution to complete and returns results inline (max 5 min timeout)
     *
     * @param {BrowserUse.WorkflowExecuteRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.executeWorkflow({
     *         workflow_id: "workflow_id"
     *     })
     */
    public executeWorkflow(
        request: BrowserUse.WorkflowExecuteRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.ExecuteWorkflowWorkflowsWorkflowIdExecutePostResponse> {
        return core.HttpResponsePromise.fromPromise(this.__executeWorkflow(request, requestOptions));
    }

    private async __executeWorkflow(
        request: BrowserUse.WorkflowExecuteRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.ExecuteWorkflowWorkflowsWorkflowIdExecutePostResponse>> {
        const { workflow_id: workflowId, ..._body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}/execute`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.ExecuteWorkflowWorkflowsWorkflowIdExecutePostResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling POST /workflows/{workflow_id}/execute.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Generate a workflow from a natural language task description.
     *
     * This endpoint uses the workflow-use library's HealingService to:
     * 1. Record browser interactions for the task
     * 2. Convert interactions to a reusable workflow
     * 3. Extract variables for parameterization
     * 4. Save the generated YAML to S3
     *
     * The generation happens asynchronously via the workflow_worker Lambda.
     *
     * @param {BrowserUse.WorkflowGenerateRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.generateWorkflow({
     *         workflow_id: "workflow_id",
     *         taskPrompt: "Go to github.com and search for browser-use"
     *     })
     */
    public generateWorkflow(
        request: BrowserUse.WorkflowGenerateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowGenerateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__generateWorkflow(request, requestOptions));
    }

    private async __generateWorkflow(
        request: BrowserUse.WorkflowGenerateRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowGenerateResponse>> {
        const { workflow_id: workflowId, ..._body } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId)}/generate`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowGenerateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling POST /workflows/{workflow_id}/generate.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get detailed execution information including status, results, and costs.
     *
     * @param {BrowserUse.GetExecutionWorkflowsExecutionsExecutionIdGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getExecution({
     *         execution_id: "execution_id"
     *     })
     */
    public getExecution(
        request: BrowserUse.GetExecutionWorkflowsExecutionsExecutionIdGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getExecution(request, requestOptions));
    }

    private async __getExecution(
        request: BrowserUse.GetExecutionWorkflowsExecutionsExecutionIdGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowExecutionResponse>> {
        const { execution_id: executionId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/executions/${encodeURIComponent(executionId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowExecutionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling GET /workflows/executions/{execution_id}.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get paginated list of executions for a specific workflow.
     *
     * @param {BrowserUse.ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.listWorkflowExecutions({
     *         workflow_id: "workflow_id"
     *     })
     */
    public listWorkflowExecutions(
        request: BrowserUse.ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowExecutionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listWorkflowExecutions(request, requestOptions));
    }

    private async __listWorkflowExecutions(
        request: BrowserUse.ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowExecutionListResponse>> {
        const { workflow_id: workflowId, pageSize, pageNumber, status, workflowId: workflowId_ } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams["pageSize"] = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams["pageNumber"] = pageNumber.toString();
        }

        if (status !== undefined) {
            _queryParams["status"] = status;
        }

        if (workflowId_ !== undefined) {
            _queryParams["workflowId"] = workflowId_;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/${encodeURIComponent(workflowId_ ?? "null")}/executions`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.WorkflowExecutionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling GET /workflows/{workflow_id}/executions.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get paginated list of all workflow executions for a project.
     *
     * @param {BrowserUse.ListAllExecutionsWorkflowsExecutionsGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.listAllExecutions()
     */
    public listAllExecutions(
        request: BrowserUse.ListAllExecutionsWorkflowsExecutionsGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowExecutionListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAllExecutions(request, requestOptions));
    }

    private async __listAllExecutions(
        request: BrowserUse.ListAllExecutionsWorkflowsExecutionsGetRequest = {},
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowExecutionListResponse>> {
        const { pageSize, pageNumber, status, workflowId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams["pageSize"] = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams["pageNumber"] = pageNumber.toString();
        }

        if (status !== undefined) {
            _queryParams["status"] = status;
        }

        if (workflowId !== undefined) {
            _queryParams["workflowId"] = workflowId;
        }

        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "workflows/executions",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.WorkflowExecutionListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /workflows/executions.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Cancel a pending or running workflow execution.
     *
     * @param {BrowserUse.CancelExecutionWorkflowsExecutionsExecutionIdCancelPatchRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.cancelExecution({
     *         execution_id: "execution_id"
     *     })
     */
    public cancelExecution(
        request: BrowserUse.CancelExecutionWorkflowsExecutionsExecutionIdCancelPatchRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowExecutionResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cancelExecution(request, requestOptions));
    }

    private async __cancelExecution(
        request: BrowserUse.CancelExecutionWorkflowsExecutionsExecutionIdCancelPatchRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowExecutionResponse>> {
        const { execution_id: executionId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/executions/${encodeURIComponent(executionId)}/cancel`,
            ),
            method: "PATCH",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.WorkflowExecutionResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling PATCH /workflows/executions/{execution_id}/cancel.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get presigned URL to download execution logs.
     *
     * @param {BrowserUse.GetExecutionLogsWorkflowsExecutionsExecutionIdLogsGetRequest} request
     * @param {Workflows.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.workflows.getExecutionLogs({
     *         execution_id: "execution_id"
     *     })
     */
    public getExecutionLogs(
        request: BrowserUse.GetExecutionLogsWorkflowsExecutionsExecutionIdLogsGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.WorkflowExecutionLogResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getExecutionLogs(request, requestOptions));
    }

    private async __getExecutionLogs(
        request: BrowserUse.GetExecutionLogsWorkflowsExecutionsExecutionIdLogsGetRequest,
        requestOptions?: Workflows.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.WorkflowExecutionLogResponse>> {
        const { execution_id: executionId } = request;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `workflows/executions/${encodeURIComponent(executionId)}/logs`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.WorkflowExecutionLogResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling GET /workflows/executions/{execution_id}/logs.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders() {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
