/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as BrowserUse from "../../../../index.js";

/**
 * @example
 *     {
 *         session_id: "session_id",
 *         body: {
 *             fileName: "fileName",
 *             contentType: "image/jpg",
 *             sizeBytes: 1
 *         }
 *     }
 */
export interface BrowserSessionUploadFilePresignedUrlFilesBrowsersSessionIdPresignedUrlPostRequest {
    session_id: string;
    body: BrowserUse.UploadFileRequest;
}
