/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BrowserUseClient } from "../../src/Client";

describe("Billing", () => {
    test("getAccountBilling", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            name: "name",
            monthlyCreditsBalanceUsd: 1.1,
            additionalCreditsBalanceUsd: 1.1,
            totalCreditsBalanceUsd: 1.1,
            rateLimit: 1,
            planInfo: {
                planName: "planName",
                subscriptionStatus: "subscriptionStatus",
                subscriptionId: "subscriptionId",
                subscriptionCurrentPeriodEnd: "subscriptionCurrentPeriodEnd",
                subscriptionCanceledAt: "subscriptionCanceledAt",
            },
            projectId: "projectId",
        };
        server.mockEndpoint().get("/billing/account").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.billing.getAccountBilling();
        expect(response).toEqual({
            name: "name",
            monthlyCreditsBalanceUsd: 1.1,
            additionalCreditsBalanceUsd: 1.1,
            totalCreditsBalanceUsd: 1.1,
            rateLimit: 1,
            planInfo: {
                planName: "planName",
                subscriptionStatus: "subscriptionStatus",
                subscriptionId: "subscriptionId",
                subscriptionCurrentPeriodEnd: "subscriptionCurrentPeriodEnd",
                subscriptionCanceledAt: "subscriptionCanceledAt",
            },
            projectId: "projectId",
        });
    });
});
