// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Browsers", () => {
    test("listBrowserSessions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    status: "active",
                    liveUrl: "liveUrl",
                    cdpUrl: "cdpUrl",
                    timeoutAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    proxyUsedMb: "proxyUsedMb",
                    proxyCost: "proxyCost",
                    browserCost: "browserCost",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server.mockEndpoint().get("/browsers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.browsers.listBrowserSessions();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    status: "active",
                    liveUrl: "liveUrl",
                    cdpUrl: "cdpUrl",
                    timeoutAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    proxyUsedMb: "proxyUsedMb",
                    proxyCost: "proxyCost",
                    browserCost: "browserCost",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listBrowserSessions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/browsers").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.browsers.listBrowserSessions();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createBrowserSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        };
        server
            .mockEndpoint()
            .post("/browsers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.browsers.createBrowserSession();
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        });
    });

    test("createBrowserSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/browsers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.createBrowserSession();
        }).rejects.toThrow(BrowserUse.ForbiddenError);
    });

    test("createBrowserSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/browsers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.createBrowserSession();
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("createBrowserSession (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/browsers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.createBrowserSession();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createBrowserSession (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/browsers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.createBrowserSession();
        }).rejects.toThrow(BrowserUse.TooManyRequestsError);
    });

    test("getBrowserSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        };
        server
            .mockEndpoint()
            .get("/browsers/session_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.browsers.getBrowserSession({
            session_id: "session_id",
        });
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        });
    });

    test("getBrowserSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/browsers/session_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.getBrowserSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getBrowserSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/browsers/session_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.getBrowserSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("updateBrowserSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        };
        server
            .mockEndpoint()
            .patch("/browsers/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.browsers.updateBrowserSession({
            session_id: "session_id",
            action: "stop",
        });
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            cdpUrl: "cdpUrl",
            timeoutAt: "2024-01-15T09:30:00Z",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
            browserCost: "browserCost",
        });
    });

    test("updateBrowserSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/browsers/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.updateBrowserSession({
                session_id: "session_id",
                action: "stop",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("updateBrowserSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/browsers/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.browsers.updateBrowserSession({
                session_id: "session_id",
                action: "stop",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });
});
