// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Files", () => {
    test("agentSessionUploadFilePresignedUrl (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "fileName", contentType: "image/jpg", sizeBytes: 1 };
        const rawResponseBody = {
            url: "url",
            method: "POST",
            fields: { key: "value" },
            fileName: "fileName",
            expiresIn: 1,
        };
        server
            .mockEndpoint()
            .post("/files/sessions/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.agentSessionUploadFilePresignedUrl({
            session_id: "session_id",
            body: {
                fileName: "fileName",
                contentType: "image/jpg",
                sizeBytes: 1,
            },
        });
        expect(response).toEqual({
            url: "url",
            method: "POST",
            fields: {
                key: "value",
            },
            fileName: "fileName",
            expiresIn: 1,
        });
    });

    test("agentSessionUploadFilePresignedUrl (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/sessions/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.agentSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("agentSessionUploadFilePresignedUrl (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/sessions/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.agentSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("agentSessionUploadFilePresignedUrl (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/sessions/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.agentSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("agentSessionUploadFilePresignedUrl (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/sessions/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.agentSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.InternalServerError);
    });

    test("browserSessionUploadFilePresignedUrl (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "fileName", contentType: "image/jpg", sizeBytes: 1 };
        const rawResponseBody = {
            url: "url",
            method: "POST",
            fields: { key: "value" },
            fileName: "fileName",
            expiresIn: 1,
        };
        server
            .mockEndpoint()
            .post("/files/browsers/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.browserSessionUploadFilePresignedUrl({
            session_id: "session_id",
            body: {
                fileName: "fileName",
                contentType: "image/jpg",
                sizeBytes: 1,
            },
        });
        expect(response).toEqual({
            url: "url",
            method: "POST",
            fields: {
                key: "value",
            },
            fileName: "fileName",
            expiresIn: 1,
        });
    });

    test("browserSessionUploadFilePresignedUrl (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/browsers/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.browserSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("browserSessionUploadFilePresignedUrl (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/browsers/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.browserSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("browserSessionUploadFilePresignedUrl (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/browsers/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.browserSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("browserSessionUploadFilePresignedUrl (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileName: "x", contentType: "image/jpg", sizeBytes: 10485760 };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/files/browsers/session_id/presigned-url")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.browserSessionUploadFilePresignedUrl({
                session_id: "session_id",
                body: {
                    fileName: "x",
                    contentType: "image/jpg",
                    sizeBytes: 10485760,
                },
            });
        }).rejects.toThrow(BrowserUse.InternalServerError);
    });

    test("getTaskOutputFilePresignedUrl (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { id: "id", fileName: "fileName", downloadUrl: "downloadUrl" };
        server
            .mockEndpoint()
            .get("/files/tasks/task_id/output-files/file_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.files.getTaskOutputFilePresignedUrl({
            task_id: "task_id",
            file_id: "file_id",
        });
        expect(response).toEqual({
            id: "id",
            fileName: "fileName",
            downloadUrl: "downloadUrl",
        });
    });

    test("getTaskOutputFilePresignedUrl (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/files/tasks/task_id/output-files/file_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getTaskOutputFilePresignedUrl({
                task_id: "task_id",
                file_id: "file_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getTaskOutputFilePresignedUrl (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/files/tasks/task_id/output-files/file_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getTaskOutputFilePresignedUrl({
                task_id: "task_id",
                file_id: "file_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("getTaskOutputFilePresignedUrl (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/files/tasks/task_id/output-files/file_id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.files.getTaskOutputFilePresignedUrl({
                task_id: "task_id",
                file_id: "file_id",
            });
        }).rejects.toThrow(BrowserUse.InternalServerError);
    });
});
