/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { BrowserUseClient } from "../../src/Client";

describe("Profiles", () => {
    test("listProfiles", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    name: "name",
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    cookieDomains: ["cookieDomains"],
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server.mockEndpoint().get("/profiles").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.profiles.listProfiles();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    name: "name",
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    cookieDomains: ["cookieDomains"],
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("createProfile", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .post("/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.createProfile();
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });

    test("getProfile", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .get("/profiles/profile_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.getProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });

    test("deleteBrowserProfile", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/profiles/profile_id").respondWith().statusCode(200).build();

        const response = await client.profiles.deleteBrowserProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual(undefined);
    });

    test("updateProfile", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .patch("/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.updateProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });
});
