// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("ProfilesClient", () => {
    test("listProfiles (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    name: "name",
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    cookieDomains: ["cookieDomains"],
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server.mockEndpoint().get("/profiles").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.profiles.listProfiles();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    name: "name",
                    lastUsedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                    cookieDomains: ["cookieDomains"],
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listProfiles (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/profiles").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.profiles.listProfiles();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .post("/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.createProfile();
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });

    test("createProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.createProfile();
        }).rejects.toThrow(BrowserUse.PaymentRequiredError);
    });

    test("createProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/profiles")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.createProfile();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("getProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .get("/profiles/profile_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.getProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });

    test("getProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/profiles/profile_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.getProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/profiles/profile_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.getProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("deleteBrowserProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/profiles/profile_id").respondWith().statusCode(200).build();

        const response = await client.profiles.deleteBrowserProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteBrowserProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/profiles/profile_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.deleteBrowserProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("updateProfile (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        };
        server
            .mockEndpoint()
            .patch("/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.profiles.updateProfile({
            profile_id: "profile_id",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            lastUsedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
            cookieDomains: ["cookieDomains"],
        });
    });

    test("updateProfile (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.updateProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("updateProfile (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/profiles/profile_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.profiles.updateProfile({
                profile_id: "profile_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });
});
