// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Sessions", () => {
    test("listSessions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    status: "active",
                    liveUrl: "liveUrl",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    persistMemory: true,
                    keepAlive: true,
                    proxyUsedMb: "proxyUsedMb",
                    proxyCost: "proxyCost",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server.mockEndpoint().get("/sessions").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.sessions.listSessions();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    status: "active",
                    liveUrl: "liveUrl",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    persistMemory: true,
                    keepAlive: true,
                    proxyUsedMb: "proxyUsedMb",
                    proxyCost: "proxyCost",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listSessions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/sessions").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.sessions.listSessions();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        };
        server
            .mockEndpoint()
            .post("/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.createSession();
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        });
    });

    test("createSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSession();
        }).rejects.toThrow(BrowserUse.PaymentRequiredError);
    });

    test("createSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSession();
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("createSession (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSession();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createSession (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/sessions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSession();
        }).rejects.toThrow(BrowserUse.TooManyRequestsError);
    });

    test("getSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            tasks: [
                {
                    id: "id",
                    sessionId: "sessionId",
                    llm: "llm",
                    task: "task",
                    status: "created",
                    createdAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    metadata: { key: "value" },
                    output: "output",
                    browserUseVersion: "browserUseVersion",
                    isSuccess: true,
                    judgement: "judgement",
                    judgeVerdict: true,
                    cost: "cost",
                },
            ],
            publicShareUrl: "publicShareUrl",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        };
        server
            .mockEndpoint()
            .get("/sessions/session_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.getSession({
            session_id: "session_id",
        });
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            tasks: [
                {
                    id: "id",
                    sessionId: "sessionId",
                    llm: "llm",
                    task: "task",
                    status: "created",
                    createdAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    metadata: {
                        key: "value",
                    },
                    output: "output",
                    browserUseVersion: "browserUseVersion",
                    isSuccess: true,
                    judgement: "judgement",
                    judgeVerdict: true,
                    cost: "cost",
                },
            ],
            publicShareUrl: "publicShareUrl",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        });
    });

    test("getSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sessions/session_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.getSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sessions/session_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.getSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("deleteSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/sessions/session_id").respondWith().statusCode(200).build();

        const response = await client.sessions.deleteSession({
            session_id: "session_id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/sessions/session_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.deleteSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("deleteSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/sessions/session_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.deleteSession({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("updateSession (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = {
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            tasks: [
                {
                    id: "id",
                    sessionId: "sessionId",
                    llm: "llm",
                    task: "task",
                    status: "created",
                    createdAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    metadata: { key: "value" },
                    output: "output",
                    browserUseVersion: "browserUseVersion",
                    isSuccess: true,
                    judgement: "judgement",
                    judgeVerdict: true,
                    cost: "cost",
                },
            ],
            publicShareUrl: "publicShareUrl",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        };
        server
            .mockEndpoint()
            .patch("/sessions/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.updateSession({
            session_id: "session_id",
            action: "stop",
        });
        expect(response).toEqual({
            id: "id",
            status: "active",
            liveUrl: "liveUrl",
            startedAt: "2024-01-15T09:30:00Z",
            finishedAt: "2024-01-15T09:30:00Z",
            tasks: [
                {
                    id: "id",
                    sessionId: "sessionId",
                    llm: "llm",
                    task: "task",
                    status: "created",
                    createdAt: "2024-01-15T09:30:00Z",
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    metadata: {
                        key: "value",
                    },
                    output: "output",
                    browserUseVersion: "browserUseVersion",
                    isSuccess: true,
                    judgement: "judgement",
                    judgeVerdict: true,
                    cost: "cost",
                },
            ],
            publicShareUrl: "publicShareUrl",
            persistMemory: true,
            keepAlive: true,
            proxyUsedMb: "proxyUsedMb",
            proxyCost: "proxyCost",
        });
    });

    test("updateSession (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sessions/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.updateSession({
                session_id: "session_id",
                action: "stop",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("updateSession (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { action: "stop" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/sessions/session_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.updateSession({
                session_id: "session_id",
                action: "stop",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("getSessionPublicShare (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            shareToken: "shareToken",
            shareUrl: "shareUrl",
            viewCount: 1,
            lastViewedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.getSessionPublicShare({
            session_id: "session_id",
        });
        expect(response).toEqual({
            shareToken: "shareToken",
            shareUrl: "shareUrl",
            viewCount: 1,
            lastViewedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getSessionPublicShare (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.getSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getSessionPublicShare (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.getSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createSessionPublicShare (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            shareToken: "shareToken",
            shareUrl: "shareUrl",
            viewCount: 1,
            lastViewedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sessions.createSessionPublicShare({
            session_id: "session_id",
        });
        expect(response).toEqual({
            shareToken: "shareToken",
            shareUrl: "shareUrl",
            viewCount: 1,
            lastViewedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("createSessionPublicShare (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("createSessionPublicShare (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.createSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("deleteSessionPublicShare (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/sessions/session_id/public-share").respondWith().statusCode(200).build();

        const response = await client.sessions.deleteSessionPublicShare({
            session_id: "session_id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteSessionPublicShare (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.deleteSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("deleteSessionPublicShare (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/sessions/session_id/public-share")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sessions.deleteSessionPublicShare({
                session_id: "session_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });
});
