// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("Skills", () => {
    test("listSkills (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    description: "description",
                    categories: ["search"],
                    domains: ["domains"],
                    goal: "goal",
                    agentPrompt: "agentPrompt",
                    status: "recording",
                    parameters: [{ name: "name", type: "string" }],
                    outputSchema: { key: "value" },
                    isEnabled: true,
                    isPublic: true,
                    iconUrl: "iconUrl",
                    firstPublishedAt: "2024-01-15T09:30:00Z",
                    lastPublishedAt: "2024-01-15T09:30:00Z",
                    currentVersion: 1,
                    currentVersionStartedAt: "2024-01-15T09:30:00Z",
                    currentVersionFinishedAt: "2024-01-15T09:30:00Z",
                    code: "code",
                    clonedFromSkillId: "clonedFromSkillId",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server.mockEndpoint().get("/skills").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.skills.listSkills();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    description: "description",
                    categories: ["search"],
                    domains: ["domains"],
                    goal: "goal",
                    agentPrompt: "agentPrompt",
                    status: "recording",
                    parameters: [
                        {
                            name: "name",
                            type: "string",
                        },
                    ],
                    outputSchema: {
                        key: "value",
                    },
                    isEnabled: true,
                    isPublic: true,
                    iconUrl: "iconUrl",
                    firstPublishedAt: "2024-01-15T09:30:00Z",
                    lastPublishedAt: "2024-01-15T09:30:00Z",
                    currentVersion: 1,
                    currentVersionStartedAt: "2024-01-15T09:30:00Z",
                    currentVersionFinishedAt: "2024-01-15T09:30:00Z",
                    code: "code",
                    clonedFromSkillId: "clonedFromSkillId",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listSkills (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/skills").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.listSkills();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { goal: "goal", agentPrompt: "agentPrompt" };
        const rawResponseBody = { id: "id" };
        server
            .mockEndpoint()
            .post("/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.createSkill({
            goal: "goal",
            agentPrompt: "agentPrompt",
        });
        expect(response).toEqual({
            id: "id",
        });
    });

    test("createSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { goal: "goal", agentPrompt: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createSkill({
                goal: "goal",
                agentPrompt: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("createSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { goal: "goal", agentPrompt: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createSkill({
                goal: "goal",
                agentPrompt: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.PaymentRequiredError);
    });

    test("createSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { goal: "goal", agentPrompt: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createSkill({
                goal: "goal",
                agentPrompt: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("createSkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { goal: "goal", agentPrompt: "strawberry" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/skills")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.createSkill({
                goal: "goal",
                agentPrompt: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.TooManyRequestsError);
    });

    test("getSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server.mockEndpoint().get("/skills/skill_id").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.skills.getSkill({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/skills/skill_id").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.getSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/skills/skill_id").respondWith().statusCode(422).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.skills.getSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("deleteSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/skills/skill_id").respondWith().statusCode(200).build();

        const response = await client.skills.deleteSkill({
            skill_id: "skill_id",
        });
        expect(response).toEqual(undefined);
    });

    test("deleteSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/skills/skill_id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("deleteSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/skills/skill_id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("deleteSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .delete("/skills/skill_id")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.deleteSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("updateSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .patch("/skills/skill_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.updateSkill({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("updateSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/skills/skill_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.ForbiddenError);
    });

    test("updateSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/skills/skill_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("updateSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .patch("/skills/skill_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.updateSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("cancelGeneration (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/skills/skill_id/cancel")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.cancelGeneration({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("cancelGeneration (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/cancel")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.cancelGeneration({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("cancelGeneration (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/cancel")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.cancelGeneration({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("cancelGeneration (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/cancel")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.cancelGeneration({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("rollbackSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/skills/skill_id/rollback")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.rollbackSkill({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("rollbackSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/rollback")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.rollbackSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("rollbackSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/rollback")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.rollbackSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("rollbackSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/rollback")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.rollbackSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("executeSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            success: true,
            result: { key: "value" },
            error: "error",
            stderr: "stderr",
            latencyMs: 1,
        };
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.executeSkill({
            skill_id: "skill_id",
            body: {},
        });
        expect(response).toEqual({
            success: true,
            result: {
                key: "value",
            },
            error: "error",
            stderr: "stderr",
            latencyMs: 1,
        });
    });

    test("executeSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("executeSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.PaymentRequiredError);
    });

    test("executeSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("executeSkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("executeSkill (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.TooManyRequestsError);
    });

    test("refineSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "feedback" };
        const rawResponseBody = { id: "id" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/refine")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.refineSkill({
            skill_id: "skill_id",
            feedback: "feedback",
        });
        expect(response).toEqual({
            id: "id",
        });
    });

    test("refineSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/refine")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.refineSkill({
                skill_id: "skill_id",
                feedback: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("refineSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/refine")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.refineSkill({
                skill_id: "skill_id",
                feedback: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("refineSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "strawberry" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/skills/skill_id/refine")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.refineSkill({
                skill_id: "skill_id",
                feedback: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("refineSkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { feedback: "strawberry" };
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/skills/skill_id/refine")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.refineSkill({
                skill_id: "skill_id",
                feedback: "strawberry",
            });
        }).rejects.toThrow(BrowserUse.TooManyRequestsError);
    });

    test("listSkillExecutions (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    skillId: "skillId",
                    status: "status",
                    success: true,
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    latencyMs: 1,
                    hasOutput: true,
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.listSkillExecutions({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    skillId: "skillId",
                    status: "status",
                    success: true,
                    startedAt: "2024-01-15T09:30:00Z",
                    finishedAt: "2024-01-15T09:30:00Z",
                    latencyMs: 1,
                    hasOutput: true,
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listSkillExecutions (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.listSkillExecutions({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("listSkillExecutions (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.listSkillExecutions({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("getSkillExecutionOutput (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { downloadUrl: "downloadUrl" };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions/execution_id/output")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skills.getSkillExecutionOutput({
            skill_id: "skill_id",
            execution_id: "execution_id",
        });
        expect(response).toEqual({
            downloadUrl: "downloadUrl",
        });
    });

    test("getSkillExecutionOutput (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions/execution_id/output")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.getSkillExecutionOutput({
                skill_id: "skill_id",
                execution_id: "execution_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getSkillExecutionOutput (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/skills/skill_id/executions/execution_id/output")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skills.getSkillExecutionOutput({
                skill_id: "skill_id",
                execution_id: "execution_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });
});
