// This file was auto-generated by Fern from our API Definition.

import * as BrowserUse from "../../src/api/index";
import { BrowserUseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("SkillsMarketplace", () => {
    test("listSkills (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            items: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    description: "description",
                    categories: ["search"],
                    domains: ["domains"],
                    parameters: [{ name: "name", type: "string" }],
                    outputSchema: { key: "value" },
                    currentVersion: 1,
                    isOfficial: true,
                    cloneCount: 1,
                    iconUrl: "iconUrl",
                    firstPublishedAt: "2024-01-15T09:30:00Z",
                    lastPublishedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        };
        server
            .mockEndpoint()
            .get("/marketplace/skills")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skillsMarketplace.listSkills();
        expect(response).toEqual({
            items: [
                {
                    id: "id",
                    slug: "slug",
                    title: "title",
                    description: "description",
                    categories: ["search"],
                    domains: ["domains"],
                    parameters: [
                        {
                            name: "name",
                            type: "string",
                        },
                    ],
                    outputSchema: {
                        key: "value",
                    },
                    currentVersion: 1,
                    isOfficial: true,
                    cloneCount: 1,
                    iconUrl: "iconUrl",
                    firstPublishedAt: "2024-01-15T09:30:00Z",
                    lastPublishedAt: "2024-01-15T09:30:00Z",
                    createdAt: "2024-01-15T09:30:00Z",
                    updatedAt: "2024-01-15T09:30:00Z",
                },
            ],
            totalItems: 1,
            pageNumber: 1,
            pageSize: 1,
        });
    });

    test("listSkills (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/marketplace/skills")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.listSkills();
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("getSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            currentVersion: 1,
            isOfficial: true,
            cloneCount: 1,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .get("/marketplace/skills/skill_slug")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skillsMarketplace.getSkill({
            skill_slug: "skill_slug",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            currentVersion: 1,
            isOfficial: true,
            cloneCount: 1,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("getSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/marketplace/skills/skill_slug")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.getSkill({
                skill_slug: "skill_slug",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("getSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/marketplace/skills/skill_slug")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.getSkill({
                skill_slug: "skill_slug",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("cloneSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: { key: "value" },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: { key: "value" },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/clone")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skillsMarketplace.cloneSkill({
            skill_id: "skill_id",
        });
        expect(response).toEqual({
            id: "id",
            slug: "slug",
            title: "title",
            description: "description",
            categories: ["search"],
            domains: ["domains"],
            goal: "goal",
            agentPrompt: "agentPrompt",
            status: "recording",
            parameters: [
                {
                    name: "name",
                    type: "string",
                    required: true,
                    description: "description",
                    default: {
                        key: "value",
                    },
                    cookieDomain: "cookieDomain",
                },
            ],
            outputSchema: {
                key: "value",
            },
            isEnabled: true,
            isPublic: true,
            iconUrl: "iconUrl",
            firstPublishedAt: "2024-01-15T09:30:00Z",
            lastPublishedAt: "2024-01-15T09:30:00Z",
            currentVersion: 1,
            currentVersionStartedAt: "2024-01-15T09:30:00Z",
            currentVersionFinishedAt: "2024-01-15T09:30:00Z",
            code: "code",
            clonedFromSkillId: "clonedFromSkillId",
            createdAt: "2024-01-15T09:30:00Z",
            updatedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("cloneSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/clone")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.cloneSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("cloneSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/clone")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.cloneSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("cloneSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/clone")
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.cloneSkill({
                skill_id: "skill_id",
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });

    test("executeSkill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            success: true,
            result: { key: "value" },
            error: "error",
            stderr: "stderr",
            latencyMs: 1,
        };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.skillsMarketplace.executeSkill({
            skill_id: "skill_id",
            body: {},
        });
        expect(response).toEqual({
            success: true,
            result: {
                key: "value",
            },
            error: "error",
            stderr: "stderr",
            latencyMs: 1,
        });
    });

    test("executeSkill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.BadRequestError);
    });

    test("executeSkill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(402)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.PaymentRequiredError);
    });

    test("executeSkill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.NotFoundError);
    });

    test("executeSkill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new BrowserUseClient({ apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/marketplace/skills/skill_id/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.skillsMarketplace.executeSkill({
                skill_id: "skill_id",
                body: {},
            });
        }).rejects.toThrow(BrowserUse.UnprocessableEntityError);
    });
});
