// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import * as BrowserUse from "../../../index.js";

export declare namespace SkillsMarketplace {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class SkillsMarketplace {
    protected readonly _options: SkillsMarketplace.Options;

    constructor(_options: SkillsMarketplace.Options) {
        this._options = _options;
    }

    /**
     * List all public skills available in the marketplace with optional filtering.
     *
     * @param {BrowserUse.ListSkillsMarketplaceSkillsGetRequest} request
     * @param {SkillsMarketplace.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.skillsMarketplace.listSkills()
     */
    public listSkills(
        request: BrowserUse.ListSkillsMarketplaceSkillsGetRequest = {},
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.MarketplaceSkillListResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listSkills(request, requestOptions));
    }

    private async __listSkills(
        request: BrowserUse.ListSkillsMarketplaceSkillsGetRequest = {},
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.MarketplaceSkillListResponse>> {
        const { pageSize, pageNumber, query, fromDate, toDate } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (pageSize != null) {
            _queryParams.pageSize = pageSize.toString();
        }

        if (pageNumber != null) {
            _queryParams.pageNumber = pageNumber.toString();
        }

        if (query !== undefined) {
            _queryParams.query = query;
        }

        if (fromDate !== undefined) {
            _queryParams.fromDate = fromDate;
        }

        if (toDate !== undefined) {
            _queryParams.toDate = toDate;
        }

        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                "marketplace/skills",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as BrowserUse.MarketplaceSkillListResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError("Timeout exceeded when calling GET /marketplace/skills.");
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get details of a specific public skill from the marketplace.
     *
     * @param {BrowserUse.GetSkillMarketplaceSkillsSkillIdGetRequest} request
     * @param {SkillsMarketplace.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.skillsMarketplace.getSkill({
     *         skill_id: "skill_id"
     *     })
     */
    public getSkill(
        request: BrowserUse.GetSkillMarketplaceSkillsSkillIdGetRequest,
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.MarketplaceSkillResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getSkill(request, requestOptions));
    }

    private async __getSkill(
        request: BrowserUse.GetSkillMarketplaceSkillsSkillIdGetRequest,
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.MarketplaceSkillResponse>> {
        const { skill_id: skillId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `marketplace/skills/${core.url.encodePathParam(skillId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.MarketplaceSkillResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling GET /marketplace/skills/{skill_id}.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Clone a public marketplace skill to the user's project.
     *
     * @param {BrowserUse.CloneSkillMarketplaceSkillsSkillIdClonePostRequest} request
     * @param {SkillsMarketplace.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link BrowserUse.BadRequestError}
     * @throws {@link BrowserUse.NotFoundError}
     * @throws {@link BrowserUse.UnprocessableEntityError}
     *
     * @example
     *     await client.skillsMarketplace.cloneSkill({
     *         skill_id: "skill_id"
     *     })
     */
    public cloneSkill(
        request: BrowserUse.CloneSkillMarketplaceSkillsSkillIdClonePostRequest,
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): core.HttpResponsePromise<BrowserUse.MarketplaceSkillResponse> {
        return core.HttpResponsePromise.fromPromise(this.__cloneSkill(request, requestOptions));
    }

    private async __cloneSkill(
        request: BrowserUse.CloneSkillMarketplaceSkillsSkillIdClonePostRequest,
        requestOptions?: SkillsMarketplace.RequestOptions,
    ): Promise<core.WithRawResponse<BrowserUse.MarketplaceSkillResponse>> {
        const { skill_id: skillId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ ...(await this._getCustomAuthorizationHeaders()) }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.BrowserUseEnvironment.Production,
                `marketplace/skills/${core.url.encodePathParam(skillId)}/clone`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as BrowserUse.MarketplaceSkillResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new BrowserUse.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 404:
                    throw new BrowserUse.NotFoundError(_response.error.body as unknown, _response.rawResponse);
                case 422:
                    throw new BrowserUse.UnprocessableEntityError(
                        _response.error.body as unknown,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.BrowserUseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.BrowserUseError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.BrowserUseTimeoutError(
                    "Timeout exceeded when calling POST /marketplace/skills/{skill_id}/clone.",
                );
            case "unknown":
                throw new errors.BrowserUseError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getCustomAuthorizationHeaders(): Promise<Record<string, string | undefined>> {
        const apiKeyValue = await core.Supplier.get(this._options.apiKey);
        return { "X-Browser-Use-API-Key": apiKeyValue };
    }
}
