// This file was auto-generated by Fern from our API Definition.

import { Billing } from "./api/resources/billing/client/Client.js";
import { Browsers } from "./api/resources/browsers/client/Client.js";
import { Files } from "./api/resources/files/client/Client.js";
import { Profiles } from "./api/resources/profiles/client/Client.js";
import { Sessions } from "./api/resources/sessions/client/Client.js";
import { Tasks } from "./api/resources/tasks/client/Client.js";
import { Workflows } from "./api/resources/workflows/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";

export declare namespace BrowserUseClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BrowserUseClient {
    protected readonly _options: BrowserUseClient.Options;
    protected _billing: Billing | undefined;
    protected _tasks: Tasks | undefined;
    protected _sessions: Sessions | undefined;
    protected _files: Files | undefined;
    protected _profiles: Profiles | undefined;
    protected _browsers: Browsers | undefined;
    protected _workflows: Workflows | undefined;

    constructor(_options: BrowserUseClient.Options) {
        this._options = {
            ..._options,
            logging: core.logging.createLogger(_options?.logging),
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "browser-use-sdk",
                    "X-Fern-SDK-Version": "2.0.6",
                    "User-Agent": "browser-use-sdk/2.0.6",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get billing(): Billing {
        return (this._billing ??= new Billing(this._options));
    }

    public get tasks(): Tasks {
        return (this._tasks ??= new Tasks(this._options));
    }

    public get sessions(): Sessions {
        return (this._sessions ??= new Sessions(this._options));
    }

    public get files(): Files {
        return (this._files ??= new Files(this._options));
    }

    public get profiles(): Profiles {
        return (this._profiles ??= new Profiles(this._options));
    }

    public get browsers(): Browsers {
        return (this._browsers ??= new Browsers(this._options));
    }

    public get workflows(): Workflows {
        return (this._workflows ??= new Workflows(this._options));
    }
}
