// This file was auto-generated by Fern from our API Definition.

import { BillingClient } from "./api/resources/billing/client/Client.js";
import { BrowsersClient } from "./api/resources/browsers/client/Client.js";
import { FilesClient } from "./api/resources/files/client/Client.js";
import { ProfilesClient } from "./api/resources/profiles/client/Client.js";
import { SessionsClient } from "./api/resources/sessions/client/Client.js";
import { TasksClient } from "./api/resources/tasks/client/Client.js";
import { WorkflowsClient } from "./api/resources/workflows/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace BrowserUseClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class BrowserUseClient {
    protected readonly _options: BrowserUseClient.Options;
    protected _billing: BillingClient | undefined;
    protected _tasks: TasksClient | undefined;
    protected _sessions: SessionsClient | undefined;
    protected _files: FilesClient | undefined;
    protected _profiles: ProfilesClient | undefined;
    protected _browsers: BrowsersClient | undefined;
    protected _workflows: WorkflowsClient | undefined;

    constructor(options: BrowserUseClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get tasks(): TasksClient {
        return (this._tasks ??= new TasksClient(this._options));
    }

    public get sessions(): SessionsClient {
        return (this._sessions ??= new SessionsClient(this._options));
    }

    public get files(): FilesClient {
        return (this._files ??= new FilesClient(this._options));
    }

    public get profiles(): ProfilesClient {
        return (this._profiles ??= new ProfilesClient(this._options));
    }

    public get browsers(): BrowsersClient {
        return (this._browsers ??= new BrowsersClient(this._options));
    }

    public get workflows(): WorkflowsClient {
        return (this._workflows ??= new WorkflowsClient(this._options));
    }
}
